### ISSUE TITLE
Exceeding ViewHelper arguments are ignored

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3Fluid/Fluid#10]
When specifying a ViewHelper argument that is not registered, an exception is thrown.
Currently the respective argument is simply ignored - which is very error prone.

BTW: There's a related feature request that would allow ViewHelpers to handle exceeding arguments. It would be great to integrate that at some point, but even then those ViewHelpers are expected to throw an exception if they come across unsupported arguments (see https://review.typo3.org/31708)

## Template

```html
<f:if foo="bar" />
```
## Expected output

```
Exception: Argument "foo" was not registered.
```

## Actual output

```
```

**Comment by NamelessCoder** [comment]
Acknowledged, should be implemented in base package.
