### ISSUE TITLE
xmlns definition on tags not recognized

### ISSUE THREAD

**Issue by liayn** [TYPO3Fluid/Fluid#103]
This code used to work in CMS 7 and below:
```
	<div xmlns:rx="http://typo3.org/ns/Reelworx/RxShariff/ViewHelper">
		<rx:shariff data="{url: 'http://example.com/'}" services="xing,facebook"  />
	</div>
```

The issue is that the `xmlns` is not resolved anymore. I need to put this into the `<html>`-tag in order to get this working.

**Comment by helhum** [comment]
As far as I understood, this must be solved in the adapter, as it is no standalone Fluid feature

**Comment by liayn** [comment]
Right.. found it. Will debug the Core.

**Comment by liayn** [comment]
@NamelessCoder You actually wrote a unit test to enforce this behaviour, why?
Please continue in the Core ticket: https://forge.typo3.org/issues/76155
