### ISSUE TITLE
ViewHelperExceptions should not be thrown at compile time

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3Fluid/Fluid#11]
The `ViewHelper\Exception` is meant to be thrown by ViewHelpers if they come across an unresolvable error during *rendering* (e.g. when the `count` ViewHelper gets an non-countable argument).
Currently this exception is thrown when ViewHelpers can't be resolved:

```html
<f:nonExistingViewHelper />
```

## Expected

*Parser\Exception*

## Actual

*ViewHelper\Exception*

This is important because the framework should be able to deal differently with the two cases.
E.g. in Flow we silently skip ViewHelpers that throw a `ViewHelper\Exception` in *Production* context. This should never happen for *parsing* errors.

**Comment by NamelessCoder** [comment]
Acknowledged, we need to change these types of Exceptions.
