### ISSUE TITLE
Global view helper namespace import gone?

### ISSUE THREAD

**Issue by jkphl** [TYPO3Fluid/Fluid#114]
The [documentation](https://github.com/TYPO3Fluid/Fluid/blob/master/doc/FLUID_VIEWHELPERS.md#registeringimporting-viewhelpers) describes a way to globally import a view helper namespace by calling:

```php
$view = new TemplateView();
$view->getTemplatePaths()->registerNamespace('foo', 'Vendor\\Foo\\ViewHelpers');
```

However, a method called `registerNamespace()` doesn't seem to exist on `TemplateView`. Has the support for this been removed?

**Comment by NamelessCoder** [comment]
Hi Joschi,

The docs are wrong / outdated. The method name is `addNamespace` (and there's also a plural named method which accepts multiple namespaces). See https://github.com/TYPO3Fluid/Fluid/blob/master/src/Core/ViewHelper/ViewHelperResolver.php#L87

Issue kept open to remind to update docs.

**Comment by jkphl** [comment]
@NamelessCoder Great, thanks! So the docs should be something like

```php
$view = new TemplateView();
$view->getViewHelperResolver()->addNamespace('foo', 'Vendor\\Foo\\ViewHelpers');
```

instead, correct?

**Comment by NamelessCoder** [comment]
Yes - and the line following the example is no longer correct (namespaces can be extended from within templates even if registered outside initially)

**Comment by montik** [comment]
Hi, the docs seems to be still outdated: it says 
`$view->getTemplatePaths()->addNamespace`
and not 
`$view->getViewHelperResolver()->addNamespace`
