### ISSUE TITLE
"-1 != -1" wrongly converted to boolean.

### ISSUE THREAD

**Issue by kitsunet** [TYPO3Fluid/Fluid#129]
The `BooleanParser` seems to struggle with the mentioned expression.

Running

```
<f:if condition="-1 != -1">
  <f:then>
    Then child!
  </f:then>
  <f:else>
    Else child!
  </f:else>
</f:if>
```

Will result in `Then child!` and the compiled code looks like this:

```
$array2 = array();
$array2['0'] = '-1 != -1';

$expression3 = function($context) {return "-";};
$arguments1['condition'] = TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\BooleanNode::convertToBoolean(
					$expression3(
						TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\BooleanNode::gatherContext($renderingContext, $array2)
					),
					$renderingContext
				);
```

From what I see the BooleanParser does not take `-` into account. I will try to find a fix for it.

**Comment by NamelessCoder** [comment]
If he'll forgive the notification, let's mention @mneuhaus here - he is the resident expert on the BooleanParser and maybe has a hint that can save you some time :)

**Comment by mneuhaus** [comment]
lookin into it after lunch :)

**Comment by mneuhaus** [comment]
Pullrequest waiting for review :)

**Comment by kitsunet** [comment]
Don't know the policy, but this could be closed now?

**Comment by mneuhaus** [comment]
sure it can :)
