### ISSUE TITLE
debug helper falsely stops dumping with 'see above'

### ISSUE THREAD

**Issue by TrueType** [TYPO3Fluid/Fluid#134]
TYPO3 7.6.10 fluid 7.6.0
I am dumping **$objects** of _TYPO3\CMS\Extbase\Persistence\Generic\QueryResult_. **$object** has a member **$childobjects** of _TYPO3\CMS\Extbase\Persistence\ObjectStorage_ in an MM relation. The **$object** is not fully rendered (without a plus sign), but with 'see above' marker as an **$object** before shares the same **$childobject.** That is wrong. The 'see above' should be with the **$childobject** only. Assigning the query result to the view differently **->assign('objects', array('anykey' => $objects))**, it renders everything correctly and marks the **$childobject** with 'see above' only.

**Comment by NamelessCoder** [comment]
This is the wrong place to report this problem. The debug ViewHelper you are using comes from TYPO3 CMS. The one that ships with Fluid is different, simpler.

Please report at https://forge.typo3.org/projects/typo3cms-core/issues
