### ISSUE TITLE
HtmlSpecialChars VH different behavior cached/uncached

### ISSUE THREAD

**Issue by kitsunet** [TYPO3Fluid/Fluid#142]
The HtmlSpecialCharsViewHelper has slightly different behavior when executed first time compared to afterwards.

In render the keepQuotes flag is evaluated like this:
`$keepQuotes ? ENT_NOQUOTES : ENT_QUOTES;`

While in compile that is translated to:
`(%2$s['keepQuotes'] ? ENT_NOQUOTES : ENT_COMPAT)`

So if keepQuotes was false it would first render with `ENT_QUOTES` and then when rendered from compiled state it would render with `ENT_COMPAT`.

**Comment by NamelessCoder** [comment]
Oops - that's definitely a missed rough edge. We should have ENT_QUOTES in both places.

**Comment by NamelessCoder** [comment]
Applied in https://github.com/TYPO3Fluid/Fluid/commit/36421713a58b1dcab9b34f222f434517f2d1316e
