### ISSUE TITLE
Reuse ViewHelper instances

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3Fluid/Fluid#5]
The current implementation contains a change in behavior that prevents some ViewHelpers to work as before: Previously a ViewHelper instance was reused for the same node in the structure. Now a new instance is created every time.
Aside from a potential increase in memory consumption this leads to the following problem:

```html
<f:for each="{0:1, 1:2, 2:3, 3:4}" as="foo">
	<f:cycle values="{0: 'foo', 1: 'bar', 2: 'baz'}" as="cycle">{cycle}</f:cycle>
</f:for>
```

## Expected output

```
foo
bar
baz
foo
```

## Actual output

```
foo
foo
foo
foo
```

Although we could maybe adjust the ``cycle`` ViewHelper to cater for that new behavior, it will probably break some 3rd party ViewHelpers, too.

**Comment by NamelessCoder** [comment]
Current behavior is to simply create a plain, new instance every time ViewHelperResolver is asked to create an instance - the goal being complete cleanliness and lifecycle predictability. That being said, if we can document a performance problem (in ViewHelpers *not belonging to TYPO3 or Flow and thus depending on complex DI*) I'd be happy to discuss if instance reuse should be introduced in the base package.

But for now, I would prefer to solve this one by doing two things:

1. Make the core ViewHelper(s) not depend on instance reuse but instead a ViewHelperVariableContainer storage.
2. Introduce forced instance reuse in each adapter package, in ViewHelperResolver, based simply on the class name requested. And call `resetState()` again which I think currently isn't happening.

Any objections to this strategy?

**Comment by bwaidelich** [comment]
> Make the core ViewHelper(s) not depend on instance reuse but instead a ViewHelperVariableContainer storage.

That won't work because only the ViewHelper at the *same syntax tree* location should keep it's state.
Otherwise

```html
<f:for each="{array1}" as="foo">
    <f:cycle values="{0: 'foo', 1: 'bar', 2: 'baz'}" as="cycle">{cycle}</f:cycle>
    <f:for each="{array2}" as="subfoo">
      <f:cycle values="{0: 'subfoo', 1: 'subbar', 2: 'subbaz'}" as="cycle">{cycle}</f:cycle>
    </f:for>
    <f:cycle values="{0: 'bar', 1: 'foos'}" as="cycle">{cycle}</f:cycle>
</f:for>
```

would lead to weird results.

For the same reason reusing the instance based on the class name probably won't work

**Comment by NamelessCoder** [comment]
Right; read, understood, acknowledged - but at the current time, I've got no suggestion how to handle this one. Would like hearing your suggestion!

**Comment by bwaidelich** [comment]
It's working in TYPO3.Fluid so why not re-implement it like it's done there (reuse the same instance per node)?

**Comment by NamelessCoder** [comment]
The linked commit should fix this. I think initially I got the execution logic down correctly mentally, with one exception: I forgot that each node could be rendered repeatedly and therefore that if any cloning should occur, it should be in the method that constructs the ViewHelperNode - not on each execution.

Instances still aren't reused "all the way" because each new ViewHelperNode will still create a new ViewHelper instance (requiring all DI etc. to be performed again). And *that's* the part I would insist gets done in a third-party ViewHelperResolver if it is required by the specific implementation.

**Comment by bwaidelich** [comment]
FYI: I updated and fixed my testing instance finally. You can see the incorrect behavior here: http://134.119.11.221/flowpack.viewhelpertest/standard/index?selectedPartial=cycle
