### ISSUE TITLE
Boolean ViewHelper arguments comparing numeric values behave differently

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3Fluid/Fluid#7]
Not to argue what makes more sense, but to report the *different* behavior

# "==" operator, comparing strings with integers:

```html
<f:if condition="'foo' == 0">
  <f:then>then</f:then>
  <f:else>else</f:else>
</f:if>
```

## Expected output

```
then
```

## Actual output

```
else
```

# ">=" operator, comparing strings with floats:

```html
<f:if condition="'1.1 >= 'foo'">
  <f:then>then</f:then>
  <f:else>else</f:else>
</f:if>
```

## Expected output

```
then
```

## Actual output

```
else
```

# ">" operator, comparing strings with integer:

```html
<f:if condition="'foo' > 0">
  <f:then>then</f:then>
  <f:else>else</f:else>
</f:if>
```

## Expected output

```
else
```

## Actual output

```
then
```

The reason for this new behavior is that now both $left and $right are *strings* in `BooleanNode::evaluateComparator()`. Before numeric values were converted to `NumericNode` instances with

```php
if (is_numeric($value)) {
	$this->leftSide->addChildNode(new NumericNode($value));
} else {
	$this->leftSide->addChildNode(new TextNode(preg_replace('/(^[\'"]|[\'"]$)/', '', $value)));
}
```

in the constructor.

**Comment by albe** [comment]
See also https://forge.typo3.org/issues/6757#note-17 on background explanation why that was needed

**Comment by NamelessCoder** [comment]
Can't help but chuckle a bit over these comparisons :)

I guess we have to support each one explicitly?

**Comment by bwaidelich** [comment]
> Can't help but chuckle a bit over these comparisons :)

As said, this is mainly a record of the *changed* behavior. But as Alexander wrote, it makes sense if you compare it with PHPs behavior. And for strict comparisons we'll have the `===` operator AFAIS.

Personally I find `'foo' == 0` => TRUE also weird and one should use such code in Fluid to begin with, but I could bet that people out there already rely on that behavior.

> I guess we have to support each one explicitly

This was just an extract, here's a more complete list: http://134.119.11.221/flowpack.viewhelpertest/standard/index?selectedPartial=if

We don't have to support them explicitly, just make sure that numeric values won't get casted to strings .
