### ISSUE TITLE
Handle multiple type definitions for arguments

### ISSUE THREAD

**Issue by liayn** [TYPO3Fluid/Fluid#74]
For reference: https://review.typo3.org/46422

Type annotations like `ClassA|ClassB` should be possible.

**Comment by NamelessCoder** [comment]
The specific annotation `ClassA|ClassB` is not and will not be supported natively (but can be done with manual validation of arguments including by overriding `validateArguments` in any ViewHelper) but `ClassFooBar[]` is now supported thanks to @pschriner :)
