### ISSUE TITLE
Re-Introduce escaping modifiers functionality

### ISSUE THREAD

**Issue by helhum** [TYPO3Fluid/Fluid#99]
https://github.com/TYPO3Fluid/Fluid/commit/4cdbc7419fce47f2ddbf26cb6dadf23188ce3f7c

Removed the escaping modifiers functionality. Any reasons why? Currently the escaping interceptor is enabled by default despite the request format (other than in older Fluid version, where the escaping was only enabled for format HTML). With that, most VHs become unusable in formats, where HTML escaping is not desired (json). Because of that, the escaping modifiers functionality was introduced, which can be used to disable escaping for such cases!

**Comment by NamelessCoder** [comment]
Solved by linked pull request - thanks @helhum!
